---
- hosts: endpoints
  become: true
  tasks:
  - name: stop unattended-upgrades
    command: systemctl stop unattended-upgrades

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev ens2
    when: ansible_architecture == "x86_64"

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev enp2s1
    when: ansible_architecture == "aarch64"

  - name: Ensure docker service is running
    systemd:
      name: docker
      state: started

  - name: Add edge user to docker group
    user:
      name: "{{ username }}"
      groups: "docker, systemd-journal"

  - name: Restart docker service
    command: systemctl restart docker

  - name: Run Mosquitto
    command: mosquitto -d -p 1883

  handlers:
    - name: docker status
      service: name=docker state=started
