---
- hosts: base_edge
  become: true
  tasks:
  - name: stop unattended-upgrades
    command: systemctl stop unattended-upgrades

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev ens2
    when: ansible_architecture == "x86_64"

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev enp2s1
    when: ansible_architecture == "aarch64"

  - name: set x86 arch var
    set_fact:
        arch: "amd64"

  - name: set arm64 arch var
    set_fact:
        arch: "arm64"
    when: ansible_architecture == "aarch64"

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Install docker
    apt:
      name: docker.io
      state: present

  - name: Add cloud user to docker group
    user:
      name: "{{ username }}"
      group: docker

  - name: Allow HTTP pulling from private docker registry
    shell: echo '{ "insecure-registries":["{{ registry_ip }}"] }' > /etc/docker/daemon.json

  - name: Restart docker service
    command: systemctl restart docker

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Enable ipv4 forwarding
    shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
  
  - name: Reload ip settings
    command: sysctl -p

  - name: Get KubeEdge and unarchive it
    unarchive:
      src: https://github.com/kubeedge/kubeedge/releases/download/v1.8.1/keadm-v1.8.1-linux-{{ arch }}.tar.gz
      dest: "/tmp"
      remote_src: true

  - name: Make KubeEdge executable
    file:
      dest: "/tmp/keadm-v1.8.1-linux-{{ arch }}/keadm/keadm"
      mode: +x

  - name: Move KubeEdge executable
    command: mv "/tmp/keadm-v1.8.1-linux-{{ arch }}/keadm/keadm" /usr/local/bin

  - name: Remove unneeded KubeEdge files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/tmp/keadm-v1.8.1-linux-{{ arch }}"
      - "/tmp/keadm-v1.8.1-linux-{{ arch }}.tar.gz"

