---
- hosts: edges
  become: true
  tasks:
  - name: stop unattended-upgrades
    command: systemctl stop unattended-upgrades

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev ens2
    when: ansible_architecture == "x86_64"

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev enp2s1
    when: ansible_architecture == "aarch64"

  - name: Ensure docker service is running
    systemd:
      name: docker
      state: started

  - name: Add edge user to docker group
    user:
      name: "{{ username }}"
      groups: "docker, systemd-journal"

  - name: Restart docker service
    command: systemctl restart docker

  - name: Wait for join command to be finished on cloud controller
    local_action:
      module: wait_for timeout=500
      path: /tmp/join-command.txt
    become: false

  - name: Copy the join command to the edge node
    copy: 
      src: /tmp/join-command.txt 
      dest: /tmp/join-command.txt

  - name: Join the cloud controller kubernetes server
    shell: "nohup keadm join --cloudcore-ipport={{ cloud_ip }}:10000 --token=$(cat /tmp/join-command.txt) --kubeedge-version=1.8.1"

  - name: Remove unneeded KubeEdge join command file
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /tmp/join-command.txt 

  handlers:
    - name: docker status
      service: name=docker state=started
