---
- hosts: base_cloud
  become: true
  tasks:
  - name: stop unattended-upgrades
    command: systemctl stop unattended-upgrades

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev ens2
    when: ansible_architecture == "x86_64"

  - name: add ip route
    command: ip route add default via 192.168.0.1 dev enp2s1
    when: ansible_architecture == "aarch64"

  - name: set x86 arch var
    set_fact:
        arch: "amd64"

  - name: set arm64 arch var
    set_fact:
        arch: "arm64"
    when: ansible_architecture == "aarch64"

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Install docker
    apt:
      name: docker.io
      state: present

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Enable ipv4 forwarding
    shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
  
  - name: Reload ip settings
    command: sysctl -p

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  # Use this version with KubeEdge 1.6.1
  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - kubelet=1.21.0-00
        - kubeadm=1.21.0-00
        - kubectl=1.21.0-00

  - name: Get KubeEdge and unarchive it
    unarchive:
      src: https://github.com/kubeedge/kubeedge/releases/download/v1.8.1/keadm-v1.8.1-linux-{{ arch }}.tar.gz
      dest: "/tmp"
      remote_src: true

  - name: Make KubeEdge executable
    file:
      dest: "/tmp/keadm-v1.8.1-linux-{{ arch }}/keadm/keadm"
      mode: +x

  - name: Move KubeEdge executable
    command: mv "/tmp/keadm-v1.8.1-linux-{{ arch }}/keadm/keadm" /usr/local/bin

  - name: Remove unneeded KubeEdge files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/tmp/keadm-v1.8.1-linux-{{ arch }}"
      - "/tmp/keadm-v1.8.1-linux-{{ arch }}.tar.gz"
